services:
  # database
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      # Use a "Volume" to save data permanently.
      # Even if you delete the container, 'postgres_data' keeps your users.
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sonclarus123
      - POSTGRES_DB=sonclarus_db
    ports:
      - "5432:5432"

  # redis db
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  # fastapi
  web:
    build: . # build using our dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app # sync laptop code to container
      - ./uploads:/app/uploads
    ports:
      - "8000:8000" # Open port 8000
    depends_on:
      - db
      - redis
    env_file:
      - .env

  # redis celery worker
  worker:
    build: . # Use the same Dockerfile
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - .:/app # mirror the code 
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
